### ISSUE TITLE
Feature proposals

### ISSUE THREAD

**Issue by zkochan** [pajtai/install-deep#1]
Hey, nice package!

I'd want to use this package in a monorepo but I'd need a few features. Would you accept a pull request with:

1. Adding a CLI
2. Adding the possibility of using pnpm instead of npm

**Comment by pajtai** [comment]
Yeah, that sounds neat.
I'll have to look into pnpm some. Hadn't heard about it before, and it seems useful, since npm installs can take down some servers :/ .

**Comment by zkochan** [comment]
pnpm solves a lot of issues. It is super fast an uses less disk space.

I suggest to install the pnpm@next version.

**Comment by pajtai** [comment]
Thanks @zkochan
